version: '3'
services:
  scraper:
    build:
      context: ./scraper
    volumes:
      - ./scraper:/scraper
      - data:/data
    depends_on:
      - server
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
      - data:/data

volumes:
  data:

